### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by QaiserAbbas** [hoangtaiki/ChatViewController#10]
Have someone facing memory issues, while using this repo ?
When I just open the ChatView, at first memory shoots to 500 mbs plus and get back to normal. 

Please suggest any solution

**Comment by EverglowingComet** [comment]
Hi, I am facing same issue.
And I found why this happens.
The imagePickerView inside the ChatViewController is loaded when ChatViewController is initiated.
And it is loading all the photo files from the iOS photo library and invalidate them into collection view items which is invisible to us.
It gets huge amount of memory with init.
We must remove this stage to avoid memory issue.

**Comment by iosparesh** [comment]
Getting same memory leak issue please help
