### ISSUE TITLE
Memory leaks with image picker type Slack

### ISSUE THREAD

**Issue by fury21** [hoangtaiki/ChatViewController#12]
Hi!
I open project and start chat with image picker type Slack and memory begin leaks...

**Comment by EverglowingComet** [comment]
Hi, I am facing same issue.
And I found why this happens.
The imagePickerView inside the ChatViewController is loaded when ChatViewController is initiated.
And it is loading all the photo files from the iOS photo library and invalidate them into collection view items which is invisible to us.
It gets huge amount of memory with init.
We must remove this stage to avoid memory issue.
